
name: first-workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repositroy
              uses: actions/checkout@v2
              
            - name: first-step
              run: echo "haii,madhav";

            - name: List all files
              run: ls -la

            - name: Print message
              run: echo "This file is preseneted"
