
name: first-workflow

on: pull #push changed to pull for avoid unwanted runs

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repositroy
              uses: actions/checkout@v2

            - name: Mutli-line command execution
              run: |
               echo "haii,madhav";
               ls -ltra
               
            - name: Executing shell script
              run: |
                chmod +x shell-script.sh
                ./shell-script.sh

                